steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "BUILD=$BUILD_ID"
    args:
      [
        "build",
        "--tag=gcr.io/${_PROJECT_ID}/${_APP_NAME}:$BUILD_ID",
        ".",
        "--build-arg",
        "REACT_APP_BASE_URL=${_REACT_APP_BASE_URL}",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_APP_NAME}:$BUILD_ID"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "${_APP_NAME}",
        "--image",
        "gcr.io/${_PROJECT_ID}/${_APP_NAME}:$BUILD_ID",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--quiet",
      ]
